MAT_IE_TYPES = [
    "Participating_Material",
    "Phase",
    "Property",
    "Result",
    "Microstructure",
    "Phenomenon",
    "Synthesis",
    "Material",
    "Environment",
    "Descriptor",
    "Number",
    "Amount_Unit",
    "MStructure",
    "Operation",
    "Characterization",
    "Application",
]
